baseURL: "https://adam-isaak.github.io" 
title: Adam Isaaks Portfolio
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Training
          url: training/
          weight: 2
        - name: Engagement
          url: engagement/
          weight: 3
        - name: Projects
          url: projects/
          weight: 4 
        - name: Achievements
          url: achievements/
          weight: 5
        - name: Contact
          url: contact/
          weight: 6

params:
    description: "This website hosts Adam Isaak's a physical geography undergraduate portfolio"
    author: Adam Isaak
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about", "training", "engagement", "projects", "achievements", "contact"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Adam Isaak
          subtitle: "Greetings, I am an Honours Physical Geography Undergraduate at the University of Manitoba, specializing in glaciers and geomorphology. I am currently focused on studying basal channels on the ice shelves in Antarctica. I have a background in programming which I leverage in modeling and in GIS applications. Take a look around to see what I've been up to, or feel free get in touch to say hello."
          imageUrl: "profile-picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Training
              url: training/
            - name: Engagement
              url: engagement/
            - name: Projects
              url: projects/
            - name: Achievements
              url: achievements/
            - name: Contact
              url: contact/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: Email
          url: mailto:adam.isaak@proton.me
        - name: LinkedIn
          url: https://www.linkedin.com/in/adam-isaak/
        - name: GitHub
          url: https://github.com/adam-isaak
        - name: CV
          url: resume.pdf


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Adam Isaak"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2